backend:
  name: github
  repo: YOUR-USERNAME/my-modern-blog  # 👈 apna repo naam daalna
  branch: main

media_folder: "assets/images"   # uploaded images save
public_folder: "/assets/images" # frontend se accessible

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }
